### PR TITLE
Add groot-auth-stub-service to setup script

### PR DESCRIPTION
**Pull request by sameetandpotatoes**

### CODE REVIEW

**Comment by narendasan** [comment]
We probably need some more advanced configuration in the dev script to choose auth provider.

**Comment by narendasan** [comment]
And this is an entire project but we probably need to explore some sort of more advanced supervisor to manage spinning up the services according to some manifest (perhaps based off docker). The script is reaching the limit of what is reasonable.

**Comment by sameetandpotatoes** [comment]
If they want to change AuthProvider, they just need to change `config.go`. I don't know if we need a more advanced way to do that. But yeah, I do agree that this script is reaching its limits now.

**Comment by bcongdon** [comment]
We talked about putting each service in a docker container, and managing them with docker-compose. I did something like this with the current docker image, except all the services are in one container currently.

I still think it's a bit overkill to dockerize groot, but I also agree that the startup script is reaching its limits.

**Comment by narendasan** [comment]
@sameetandpotatoes I meant picking whether the dev auth would spin up or not, but if they change the config it doesnt really matter i guess
@bcongdon I think it might be worth starting to move towards docker, it might not be overkill now, but with the rate at which we are adding services, I think it might be worth it at least for production (keeping something analogous to dev_spinup for native development).

**Comment by narendasan** [comment]
I would also like to start tagging releases for services, setting up release milestones, and automated build deployment for both beta and prod. Its a more in depth discussion but I would like to make that one of the higher priorities, as stability is still an issue. Docker might help making that easier.

**Comment by sameetandpotatoes** [comment]
@narendasan Can this be merged now?

**Pull request merged**
